_target_: trainers.unet_trainer.UNetTrainer

hyperparameters:
  skip_training: false
  max_epochs: 10
  val_every: 500
  sample_every: 10
  save_every: 10
  pretrain_image_steps: 0
  batch_size: 4
  save_dir: checkpoints
  save_name: lets_go_beast
  load_path: null  # The path to checkpoint to load from
  lr: 0.0001
  sample_steps: 250

dataloader:
  _target_: data.climate_dataset.ClimateDataLoader
  _partial_: True
  shuffle: True
  
  num_workers: 0
  pin_memory: false
  drop_last: false


optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: ${..hyperparameters.lr}


accelerator:
  mixed_precision: fp16
  split_batches: False
  gradient_accumulation_steps: 4
  log_with: wandb