_target_: diffusers.AutoencoderKL
in_channels: 2
out_channels: 2
down_block_types:
  - DownEncoderBlock2D
  - DownEncoderBlock2D
  - DownEncoderBlock2D
up_block_types:
  - UpDecoderBlock2D
  - UpDecoderBlock2D
  - UpDecoderBlock2D
block_out_channels:
  - 64
  - 128
  - 128
latent_channels: 4
act_fn: silu
sample_size: 96
