_target_: models.video_net.UNetModel3D
n_vars: 1
model_dim: 64
dim_mults: 
  - 0.75
  - 2
  - 3
  - 4
use_checkpoint: True
use_sparse_linear_attn: False
use_temp_attn: False
year_cond: False
cond_map: True
day_cond: False
attn_dim_head: 32
attn_heads: 8
init_kernel_size: 7
resnet_groups: 8