_target_: diffusers.UNet2DModel
sample_size: 96
in_channels: 1
out_channels: 1
time_embedding_type: positional
down_block_types:
  - DownBlock2D
  - DownBlock2D
  - DownBlock2D
  - AttnDownBlock2D


up_block_types:
  - AttnUpBlock2D
  - UpBlock2D
  - UpBlock2D
  - UpBlock2D

block_out_channels:
  - 64
  - 128
  - 256
  - 256

layers_per_block: 2
resnet_time_scale_shift: scale_shift
