_target_: src.models.unet_2d.Unet
dim: 128
init_dim: null
out_dim: null
dim_mults: [1, 2, 4]
self_condition: false
resnet_block_groups: 8
learned_variance: false
learned_sinusoidal_cond: false
random_fourier_features: false
learned_sinusoidal_dim: 16
sinusoidal_pos_emb_theta: 10000
attn_dim_head: 32
attn_heads: 4
full_attn: [false, false, true, true]
flash_attn: true
