_target_: imagen_pytorch.Unet3D
dim: 64
num_resnet_blocks: 1
dim_mults:
  - 1
  - 2
  - 4
  - 8
cond_images_channels: 1
channels: 1
layer_attns: False
attend_at_middle: False   
time_causal_attn: True
layer_cross_attns: False
use_linear_attn: False
use_linear_cross_attn: False
cond_on_text: False
memory_efficient: True
attn_dim_head: 16
attn_heads: 4