_target_: src.diffusers.gaussian.GaussianDiffusion
timesteps: 1000
sampling_timesteps: 1000
objective: pred_noise
beta_schedule: linear
schedule_fn_kwargs: {}
ddim_sampling_eta: 0.0
auto_normalize: True
offset_noise_strength: 0.0
min_snr_loss_weight: False
min_snr_gamma: 5
