# path to root directory
# Defaults to current working directory
root_dir: .

# Path to directory where raw netCDF4 files are stored
data_dir: /research/hutchinson/data/ml_climate/prepared_data/

# Path to where our generated samples will be saved
save_dir: /research/hutchinson/data/ml_climate/saved_samples/
