defaults:
  - _self_
  - paths: default


esm: IPSL         # The ESM you want to process
scenario: rcp85   # The scenario you want to process
var: pr          # The variable you want to process

gen_prefix: null  # If the generated data has a prefix attached to the name, specify it here

start_year: 2080  # Start year of the data to visualize
end_year: 2100    # End year of the data to visualize
