defaults:
  - _self_
  - paths: default


esm: IPSL         # The ESM you want to process
scenario: rcp85   # The scenario you want to process
num_chunks: 40    # How many chunks to split each realization into
                  # make this number as many cores as you have available

start_year: 1850  # Start year of the training data
end_year: 2100    # End year of the training data
