defaults:
  - _self_
  - data: ipsl
  - model: unet_3d
  - scheduler: ddpm
  - trainer: unet3d
  - paths: default

accelerator:
  _target_: accelerate.Accelerator
  mixed_precision: fp16
  split_batches: False
  gradient_accumulation_steps: 1
  log_with: wandb

# Seed for random number generators
seed: 50

wandb:
  project_name: diffesm
  init_kwargs:
    name: test
    mode: online
